name: Hello SaaS

on:
  workflow_dispatch:

jobs:
  Hello_SaaS_GitHub_Actions:
    runs-on: ubuntu-latest

    steps:
      # Step to print a greeting
      - name: Print Hello SaaS Team
        run: echo "Hello, SaaS Team"

      # Step to run a custom script
      - name: Run a custom script
        id: custom_scripts
        continue-on-error: false
        run: |
          echo "This is a custom script"
          mkdir -p SaaS1_Demo_Directory
          echo "script executed successfully"

      # Step to install Nginx
      - name: Install Nginx
        id: install_nginx
        continue-on-error: false
        run: |
          echo "Installing Nginx..."
          sudo apt-get update
          sudo apt-get install -y nginx
          echo "Nginx installed successfully."

      # Step to start Nginx and verify installation
      - name: Start Nginx and Check Status
        continue-on-error: false
        run: |
          echo "Starting Nginx..."
          sudo systemctl start nginx
          sudo systemctl status nginx
          echo "Nginx is running."

      # Success or failure message
      - name: Check Success or Failure Message
        if: always()
        run: |
          if [[ "${{ steps.custom_scripts.outcome }}" == "success" ]]; then
            echo "Script executed successfully!"
          else
            echo "Failed to execute the script"
            exit 1
          fi

          if [[ "${{ steps.install_nginx.outcome }}" == "success" ]]; then
            echo "Nginx installed successfully!"
          else
            echo "Failed to install Nginx"
            exit 1
          fi
