name: Run Hello_SaaS from Python Script
on:
  workflow_dispatch:

jobs:
  Hello_SaaS_GitHub_Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Corrected Python version to a valid release

      - name: Run Python Script
        run: python hello.py
