name: sendmailer
on:
  workflow_dispatch:

jobs:
  Hello_SaaS_GitHub_Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello SaaS
        run: echo "Hello SaaS"

      - name: Send Email
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: smtp.office365.com
          smtp-port: 587
          smtp-secure: true
          from-email: ${{ secrets.MAIL_ADDRESS_PRINCE }}
          to-email: prince.chithersingh@valgenesis.com
          username: ${{ secrets.MAIL_ADDRESS_PRINCE }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Test Email
          body: This is a test email sent from GitHub Actions.
          html: |
           <h1>This is a test email</h1>
           <p>We are going to perform monthly maintenance activity on Saturday  (21st Dec 2024) in our Chennai, Colocation, Azure Datacenter from 10 AM to 5 PM IST.</p>
